# Generated by Django 5.1.4 on 2025-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('last_updated_at', models.DateField(db_index=True, verbose_name='Дата запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'Место на карте',
                'verbose_name_plural': 'Места на карте',
            },
        ),
    ]
