# Generated by Django 5.1.4 on 2025-02-15 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20241031_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена товара в заказе'),
        ),
    ]
