# Generated by Django 5.1.4 on 2025-02-15 14:32

from django.db import migrations
from ..models import OrderItem


def set_price_fixed(apps, schema_editor):
    orderitems = OrderItem.objects.all()
    for orderitem in orderitems.iterator():
        orderitem.price_fixed = orderitem.product.price
        orderitem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price_fixed'),
    ]

    operations = [
        migrations.RunPython(set_price_fixed),
    ]
