# Generated by Django 5.1.4 on 2025-02-15 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20250215_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена товара в заказе'),
        ),
    ]
