# Generated by Django 5.1.4 on 2025-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderitem_price_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('proc', 'В обработке'), ('cook', 'Готовится'), ('dlvr', 'Передан в доставку'), ('end', 'Завершен')], default='proc', max_length=4),
            preserve_default=False,
        ),
    ]
