# Generated by Django 5.1.4 on 2025-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='foodcartapp_status_99d57e_idx'),
        ),
    ]
