# Generated by Django 5.1.4 on 2025-02-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('epay', 'Электронно'), ('cash', 'Наличностью')], default='cash', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
